name: NYC Collision Data Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # still midnight
  workflow_dispatch:      # mostly for testing

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: Scraper Env
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      env:
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      run: |
        python scripts/scrape.py

    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -u .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update collision data $(date +'%Y-%m-%d %H:%M:%S')" && git push)
