name: NYC Collision Data Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # midnight UTC 
  workflow_dispatch:      # can also trigger 

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sodapy requests
        
    - name: Run scraper
      run: python scrape.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add *.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update collision data for $(date +'%Y-%m-%d')" && git push)